name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: '>=1.24.0'

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: task test

      - name: Build binary
        run: task build OUTPUT_FILE_SUFFIX=".${{ github.ref_name }}"
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: binary-${{ matrix.arch }}
          path: dist/*

  package-debian:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - build
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3

      - name: Build deb archive
        run: task pkg:debian
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: deb-${{ matrix.arch }}
          path: pkg/debian/*.deb
